version: 0.8.0+{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  except:
  - pi-lighting
skip_branch_with_pr: true
configuration: Release
platform: x64
image: Visual Studio 2019

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }

before_build:
- ps: >-
    (Get-Content Project-Aurora\Project-Aurora\Properties\AssemblyInfo.cs) -replace '\[assembly: AssemblyFileVersion\("(.*)"\)\]', "[assembly: AssemblyFileVersion(`"$($env:APPVEYOR_BUILD_VERSION)`")]" | Set-Content Project-Aurora\Project-Aurora\Properties\AssemblyInfo.cs
- cmd: >-
    git submodule update --init --recursive
    
    cd Project-Aurora
    
    nuget restore
    
after_build:
- cmd: >-
    set PATH="C:\Program Files (x86)\Inno Setup 6";%PATH%
    
    ISCC.exe /DEXTERNAL_VERSION=%APPVEYOR_BUILD_VERSION% %APPVEYOR_BUILD_FOLDER%\Installer\installer.iss


build:
  project: Project-Aurora\Project-Aurora.sln
  verbosity: minimal

artifacts:
  - path: Build\Release
    name: Aurora-v$(appveyor_build_version)
    type: zip
  - path: Aurora-setup-v$(appveyor_build_version).exe
    
deploy:
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: fH71/PvnIYe92vatcu/GCBXaAHNcwGWG7Olubsw5DCUy7eHWSs7QcY2u/WalhMfg
  artifact: Build\Aurora-v$(appveyor_build_version).zip,Aurora-setup-v$(appveyor_build_version).exe          
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true