version: 0.6.0b-{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  except:
  - pi-lighting
skip_branch_with_pr: true
configuration: Release
platform: x64
before_build:
- cmd: nuget restore
build:
  project: Project-Aurora.sln
  verbosity: minimal