name: Aurora CD

on:
  push:
    branches: [ dev ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2019  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Project-Aurora/Project-Aurora.sln

    steps:
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.github_token}}
        
    - uses: rishabhgupta/split-by@v1
      id: split
      with:
        string: ${{github.repository}}
        split-by: '/'
    - run: | 
       echo "${{github.repository}}"
    - run: | 
       echo "${{ steps.split.outputs._0}}"
    - run: | 
       echo "${{ steps.split.outputs._1}}"
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Restore Nuget Cache
      uses: actions/cache@v1
      id: cache
      with:
        path: '%userprofile%\.nuget\packages'
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: NuGet Restore
      if: steps.cache.outputs.cache-hit != 'true'
      run: nuget restore $env:Solution_Name

    - name: Build
      run: dotnet build $env:Solution_Name --configuration $env:Configuration --no-restore
      env:
        APPVEYOR_BUILD_VERSION: v${{steps.buildnumber.outputs.build_number}}
        OWNER: ${{ steps.split.outputs._0 }}
        REPOSITORY: ${{ steps.split.outputs._1 }}
        Configuration: ${{ matrix.configuration }}

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Building the installer
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" /DEXTERNAL_VERSION=${{steps.buildnumber.outputs.build_number}} Installer\installer.iss
      shell: cmd
      
    - name: Archive Build
      shell: pwsh
      run: |
        Compress-Archive .\Build\Release\* Aurora-v${{steps.buildnumber.outputs.build_number}}.zip
      
    - name: Installer Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_commitish: dev
        draft: true
        files: |
          Aurora-setup-v${{steps.buildnumber.outputs.build_number}}.exe
          Aurora-v${{steps.buildnumber.outputs.build_number}}.zip
        tag_name: v${{steps.buildnumber.outputs.build_number}}
        allow_override: false
        prerelease: true

